apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/maxklema/argocd-test.git 
    targetRevision: HEAD # last commit in repository
    path: dev
  destination:
    server: https://kubernetes.default.svc 
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: # polls Git repo every 3 minutes
      selfHeal: true
      prune: true
